/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: bb8556b413ae1555c2819a24ef846761)
interface __BaseEnv_Env {
  AI: Ai;
  ResearchAgent: DurableObjectNamespace<import("./src/server").ResearchAgent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ResearchAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
