/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: 56f684e2686532aaf78d1f2876a11792)
interface __BaseEnv_Env {
  AI: Ai;
  WebFetchLabAgent: DurableObjectNamespace<
    import("./src/server").WebFetchLabAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "WebFetchLabAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
